name: release-module-zip

on:
  push:
    tags: ['v*']
  workflow_dispatch: {}

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Locate psd1 and read version
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $psd1Item = Get-ChildItem -Recurse -File -Filter 'Koronet-Axerrio.GitTools.psd1' | Select-Object -First 1
          if (-not $psd1Item) { throw "psd1 not found anywhere in repo" }
          $psd1 = $psd1Item.FullName
          $data = Import-PowerShellDataFile -Path $psd1
          if (-not $data -or -not $data.ModuleVersion) { throw "ModuleVersion missing in $psd1" }
          "PSD1_PATH=$psd1"                | Out-File -FilePath $env:GITHUB_ENV -Append
          "MOD_VER=$($data.ModuleVersion)" | Out-File -FilePath $env:GITHUB_ENV -Append
          if ($data.RootModule -and ($data.RootModule -notmatch '^[^\\/]+\.psm1$')) {
            Write-Warning "RootModule should be just the file name (e.g., Koronet-Axerrio.GitTools.psm1). Current: '$($data.RootModule)'."
          }

      - name: Enforce tag matches ModuleVersion
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $tag = "${{ github.ref_name }}".TrimStart('v')
          if ("${{ env.MOD_VER }}" -ne $tag) {
            throw "ModuleVersion ($env:MOD_VER) does not match tag v$tag"
          }

      - name: Build ZIP (package full module folder)
        run: |
          $ErrorActionPreference = 'Stop'
          $moduleName  = 'Koronet-Axerrio.GitTools'
          $psd1        = "${{ env.PSD1_PATH }}"
          $moduleRoot  = Split-Path -Parent $psd1
          $parent      = Split-Path -Parent $moduleRoot
          $zipName     = if ($env:GITHUB_REF_NAME) { "$moduleName-${{ github.ref_name }}.zip" } else { "$moduleName-manual.zip" }

          # sanity: these usually exist
          if (-not (Test-Path (Join-Path $moduleRoot 'Public')))  { Write-Warning "Missing 'Public' folder under $moduleRoot" }
          if (-not (Test-Path (Join-Path $moduleRoot 'Private'))) { Write-Warning "Missing 'Private' folder under $moduleRoot" }

          # zip the FOLDER so the archive contains a top-level Koronet-Axerrio.GitTools/
          Push-Location $parent
          if (Test-Path $zipName) { Remove-Item $zipName -Force }
          Compress-Archive -Path $moduleName -DestinationPath (Join-Path $PWD $zipName) -Force
          Pop-Location

          # log what we packed (helpful for debugging)
          Get-ChildItem $moduleRoot -Recurse | Select-Object FullName

          "ZIP_PATH=$zipName" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: koronet-axerrio-gittools-zip
          path: ${{ env.ZIP_PATH }}

      - name: Ensure bootstrap exists
        shell: pwsh
        run: |
          if (-not (Test-Path 'tools/KXGT-Bootstrap.ps1')) { throw "Bootstrap script not found at tools/KXGT-Bootstrap.ps1" }
          "BOOTSTRAP_PATH=tools/KXGT-Bootstrap.ps1" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Create GitHub Release (attach ZIP + Bootstrap)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ZIP_PATH }}
            ${{ env.BOOTSTRAP_PATH }}
            tools/Install-KXGTLatest.bat
            tools/Uninstall-KXGTLocal.bat
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
